magnitude_limit: 19
dr: 3
apply_focus_mask: True
limit_radius: 24.0
n_r_knots: 10
n_phi_knots: 15
n_time_knots: 6
n_time_points: 100
time_radius: 8
rmin: 1
rmax: 16
time_corrector: "pos_corr"
cartesian_knot_spacing: sqrt
fit_bkg: False
